version: '3'

services:
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=macapa
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password

  postgresql:
    image: postgres
    container_name: postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=varejao
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local
